export const DEFAULT_NUMBER_OF_ENTRIES_TO_START = 5;
export const DEFAULT_NUMBER_OF_ENTRIES_TO_ADD_EACH_TIME = 3;
export const MAXIMUM_NUMBER_OF_ENTRIES = 100;
export const GUEST_INSUFFICIENT_ACCESS = 'GUEST_INSUFFICIENT_ACCESS';