import genericErrorHeader from '@salesforce/label/site.checkoutErrorHandler.genericErrorHeader';
import unknownErrorBody from '@salesforce/label/site.checkoutErrorHandler.unknownErrorBody';
import noDeliveryAddressesBody from '@salesforce/label/site.checkoutErrorHandler.noDeliveryAddressesBody';
import noDeliveryMethodsErrorLabel from '@salesforce/label/site.checkoutErrorHandler.noDeliveryMethodsErrorLabel';
import insufficientInventoryBody from '@salesforce/label/site.checkoutErrorHandler.insufficientInventoryBody';
import insufficientInventoryHeader from '@salesforce/label/site.checkoutErrorHandler.insufficientInventoryHeader';
import invalidContactPhoneBody from '@salesforce/label/site.checkoutErrorHandler.invalidContactPhoneBody';
import fatalErrorBody from '@salesforce/label/site.checkoutErrorHandler.fatalErrorBody';
import returnToCart from '@salesforce/label/site.checkoutErrorHandler.returnToCart';
import returnToCheckout from '@salesforce/label/site.checkoutErrorHandler.returnToCheckout';
import paymentErrorBody from '@salesforce/label/site.checkoutErrorHandler.paymentErrorBody';
import paymentErrorHeader from '@salesforce/label/site.checkoutErrorHandler.paymentErrorHeader';
export { genericErrorHeader, unknownErrorBody, noDeliveryAddressesBody, noDeliveryMethodsErrorLabel, insufficientInventoryBody, insufficientInventoryHeader, invalidContactPhoneBody, fatalErrorBody, returnToCart, returnToCheckout, paymentErrorBody, paymentErrorHeader };